### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by zqwei** [zqwei/Im-phys-org#26]
In database:
1. Change “description” to Task decription
2. Remove blue tag for nonsimultaneous recordings
3. Remove short description of behavior
4. Remove description section of the datasets
5. Add to each dataset a line of # Animals, # sessions, # neurons

In website:

1. Delete contribute button in Analyses
2. Add a one line space in the analyses section and datasets section for brief instructions
3. Plots in distribution need x (and y) labels!
4. Remove first sentence in home page.
5. Remove “Please contact us directly if submit button is…”

**Comment by zqwei** [comment]
In database:
- [ ] Change “description” to Task decription
- [ ] Remove blue tag for nonsimultaneous recordings
- [ ] Remove short description of behavior
- [ ] Remove description section of the datasets
- [ ] Add to each dataset a line of # Animals, # sessions, # neurons

In website:

- [ ]  Delete contribute button in Analyses
- [ ]  Add a one line space in the analyses section and datasets section for brief instructions
- [ ]  Plots in distribution need x (and y) labels!
- [ ]  Remove first sentence in home page.
- [ ]  Remove “Please contact us directly if submit button is…”
